version=2.0.0
versionCode=1
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8

# Opt out of the Compose Hot Reload plugin bundled with the Compose Gradle plugin:
# as it forces JBR which may not be the system runtime.
org.jetbrains.compose.hot.reload.disable=true
